### ISSUE TITLE
Scroll into hash

### ISSUE THREAD

**Issue by ulmzr** [AlexxNB/malinajs-router#2]
Hi,
I have several hashtags in my page and need to scroll after visited page.
In App.xht
```
...
<nav>
   <a href="/home">Home</a>
   <a href="/corporate/board">Board</a>
   <a href="/corporate/policy">Policy</a>
   <a href="/corporate/contact">Contact</a>
</nav>
...
<Route path="/corporate/:hash">
   {#slot params}
      <Corporate hash={params.hash}/>
   {/slot}
</Route>
...
```
Corporate.xht
```
<script>
   export let hash
   $: hash, elem = document.getElementById(hash), elem && elem.scrollIntoView();
</script>
<h1 id="board">
...
<h1 id="policy">
...
<h1 id="contact">
```
It will be nice if I can have feature like this;
```
<nav>
   <a href="/home">Home</a>
   <a href="/corporate#board">Board</a>
   <a href="/corporate#policy">Policy</a>
   <a href="/corporate#contact">Contact</a>
</nav>
```
Thanks,

**Comment by AlexxNB** [comment]
The router may work both in history and hash mode. And these links may be  correct in history one, but won't work in hash one. I don't want that link's behaviour be different in each mode. 

I'll see if it is possible to make programmatic scroll to anchor, for this case.

**Comment by AlexxNB** [comment]
Right now you can do the trick like this:
https://malinajs.github.io/repl/#/share/Z04MghDJsc9

**Comment by ulmzr** [comment]
Thanks Alex.
